//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class pj_tyler_struct : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal pj_tyler_struct(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(pj_tyler_struct obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~pj_tyler_struct() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsuaPINVOKE.delete_pj_tyler_struct(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public short freq1 {
    set {
      pjsuaPINVOKE.pj_tyler_struct_freq1_set(swigCPtr, value);
    } 
    get {
      short ret = pjsuaPINVOKE.pj_tyler_struct_freq1_get(swigCPtr);
      return ret;
    } 
  }

  public int freq2 {
    set {
      pjsuaPINVOKE.pj_tyler_struct_freq2_set(swigCPtr, value);
    } 
    get {
      int ret = pjsuaPINVOKE.pj_tyler_struct_freq2_get(swigCPtr);
      return ret;
    } 
  }

  public string name {
    set {
      pjsuaPINVOKE.pj_tyler_struct_name_set(swigCPtr, value);
    } 
    get {
      string ret = pjsuaPINVOKE.pj_tyler_struct_name_get(swigCPtr);
      return ret;
    } 
  }

  public pj_tyler_struct() : this(pjsuaPINVOKE.new_pj_tyler_struct(), true) {
  }

}
