//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class pjsua {
  public static int add(int a, int b) {
    int ret = pjsuaPINVOKE.add(a, b);
    return ret;
  }

  public static int sub(int a1, int b1) {
    int ret = pjsuaPINVOKE.sub(a1, b1);
    return ret;
  }

}
